name: Project release on PyPi

on:
  workflow_dispatch:

jobs:
  release-on-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Hatch
        run: pip install hatch

      - name: Bump version
        run: hatch version minor

      - name: Build Haystack
        run: ./build.sh

      - name: Commit version bump
        run: git commit -am "Bump version"

      - name: Publish on PyPi
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_API_TOKEN }}
        run: hatch publish -y
